### ISSUE TITLE
how to convert multi distributed GPU to single GPU

### ISSUE THREAD

**Issue by kobrafarshidi** [HenryJunW/TAG#1]
in this project we should use multi GPU . How to change source code to could use for single GPU systems because when I run this code with system that has single GPU(Geforce gtx ti), I have error and I could not run project.
python -m torch.distributed.launch --nproc_per_node 1 tools/run.py --pretrain --tasks vqa --datasets m4c_textvqa --model m4c_split --seed 13 --config configs/vqa/m4c_textvqa/tap_base_pretrain.yml --save_dir save/m4c_split_pretrain_test training_parameters.distributed True

**Comment by HenryJunW** [comment]
What errors do you have? You might need to decrease the batch size.

**Comment by HenryJunW** [comment]
Close due to inactivity.

**Comment by kobrafarshidi** [comment]
hi,thank you for your responce and I soo sorry for delay because time of my country is different.I attached for you errors and project is from github (and my system has Geforce GTX 1080 ti GPU )microsoft/TAP: TAP: Text-Aware Pre-training for Text-VQA and Text-Caption, CVPR 2021 (Oral) (github.com)


    On Monday, September 19, 2022 at 08:53:23 AM GMT+4:30, Jun Wang ***@***.***> wrote:  
 
 


What errors do you have? You might need to decrease the batch size.

**Comment by HenryJunW** [comment]
No worries, I don't see your attachment though.

**Comment by kobrafarshidi** [comment]
Hi I am so sorry. I send you again
    On Wednesday, September 21, 2022, 07:01:26 PM GMT+4:30, Jun Wang ***@***.***> wrote:  
 
 


No worries, I don't see your attachment though.

**Comment by kobrafarshidi** [comment]
![2-q](https://user-images.githubusercontent.com/91652559/191713197-1d974103-3864-43fb-8cba-aade2a5f9a78.png)

**Comment by kobrafarshidi** [comment]
Hi, It seems I couldnt attatched error so I send here. I'd appreciate it if you could help me with it/guide me through it.

**Comment by HenryJunW** [comment]
The image you attached is low-resolution and unrecognizable. Could you copy and paste all the words here?

**Comment by kobrafarshidi** [comment]
```
(riv@riv-System-Product-Name:/media/riv/New Volume/kf/TAP$ python -m torch.distributed.launch --nproc_per_node 4 tools/run.py --pretrain --tasks vqa --datasets m4c_textvqa --model m4c_split --seed 13 --config configs/vqa/m4c_textvqa/tap_base_pretrain.yml --save_dir save/m4c_split_pretrain_test training_parameters.distributed True
/home/riv/anaconda3/envs/TAP/lib/python3.6/site-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  FutureWarning,
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Overriding option training_parameters.distributed to True
You have chosen to seed the training. This will turn on CUDNN deterministic setting which can slow down your training considerably! You may see unexpected behavior when restarting from checkpoints.
Overriding option training_parameters.distributed to True
You have chosen to seed the training. This will turn on CUDNN deterministic setting which can slow down your training considerably! You may see unexpected behavior when restarting from checkpoints.
Overriding option training_parameters.distributed to True
You have chosen to seed the training. This will turn on CUDNN deterministic setting which can slow down your training considerably! You may see unexpected behavior when restarting from checkpoints.
Overriding option training_parameters.distributed to True
You have chosen to seed the training. This will turn on CUDNN deterministic setting which can slow down your training considerably! You may see unexpected behavior when restarting from checkpoints.
Traceback (most recent call last):
  File "tools/run.py", line 92, in <module>
    run()
  File "tools/run.py", line 80, in run
    trainer.load()
  File "/media/riv/New Volume/kf/TAP/pythia/trainers/base_trainer.py", line 33, in load
    self._init_process_group()
  File "/media/riv/New Volume/kf/TAP/pythia/trainers/base_trainer.py", line 63, in _init_process_group
    synchronize()
  File "/media/riv/New Volume/kf/TAP/pythia/utils/distributed_utils.py", line 18, in synchronize
    dist.barrier()
  File "/home/riv/anaconda3/envs/TAP/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 2709, in barrier
    work = default_pg.barrier(opts=opts)
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1640811805959/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:957, invalid usage, NCCL version 21.0.3
ncclInvalidUsage: This usually reflects invalid usage of NCCL library (such as too many async ops, too many collectives at once, mixing streams in a group, etc).
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 3070518) of binary: /home/riv/anaconda3/envs/TAP/bin/python
Traceback (most recent call last):
  File "/home/riv/anaconda3/envs/TAP/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/riv/anaconda3/envs/TAP/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/riv/anaconda3/envs/TAP/lib/python3.6/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/riv/anaconda3/envs/TAP/lib/python3.6/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/riv/anaconda3/envs/TAP/lib/python3.6/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/riv/anaconda3/envs/TAP/lib/python3.6/site-packages/torch/distributed/run.py", line 713, in run
    )(*cmd_args)
  File "/home/riv/anaconda3/envs/TAP/lib/python3.6/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/riv/anaconda3/envs/TAP/lib/python3.6/site-packages/torch/distributed/launcher/api.py", line 261, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/run.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-09-11_21:08:18
  host      : riv-System-Product-Name
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3070518)
  error_file: <N/A>)
```

**Comment by kobrafarshidi** [comment]
In this case I writed for num_process 4 GPU and for 1 GPU has the same error. In the end, after consulting with the PyTorch author, I came to the conclusion that I need to modify the program in some way so that the answer can be reached with a GPU and I dont know how to change

**Comment by HenryJunW** [comment]
You are supposed to set '--nproc_per_node' with the number of your GPU following the instruction https://github.com/HenryJunW/TAG/blob/main/GETTING_STARTED.md. Since you are using 1 GPU, so could you try running, 
`python -m torch.distributed.launch --nproc_per_node 1 tools/run.py --pretrain --tasks vqa --datasets m4c_textvqa --model m4c_split --seed 13 --config configs/vqa/m4c_textvqa/tap_base_pretrain.yml --save_dir save/m4c_split_pretrain_test training_parameters.distributed True`

**Comment by kobrafarshidi** [comment]
Thank you for your response .I try this but I have same errors and not fix it.

**Comment by HenryJunW** [comment]
I'm not able to reproduce this bug.

There is one workaround:
You could try pull the updated code and re-install the conda environment by using 'conda env create --name tap --file=tag.yml' from https://github.com/HenryJunW/TAG/blob/main/INSTALL.md. 

Hope this helps.

**Comment by kobrafarshidi** [comment]
Ok.Thank you.

**Comment by PAradoxLG** [comment]
> Ok.Thank you.
Hello!Do you save this problem?I have the same problem but can't work out it.

**Comment by HenryJunW** [comment]
Can you try to disable the distributed training if you are using a single GPU by setting 'training_parameters.distributed False', 

`python -m torch.distributed.launch --nproc_per_node 1 tools/run.py --pretrain --tasks vqa --datasets m4c_textvqa --model m4c_split --seed 13 --config configs/vqa/m4c_textvqa/tap_base_pretrain.yml --save_dir save/m4c_split_pretrain_test training_parameters.distributed False`
