### ISSUE TITLE
Where is generated data？

### ISSUE THREAD

**Issue by PAradoxLG** [HenryJunW/TAG#5]
@HenryJunW Hi, thanks for you amazing project. I want to check the generated data, but I can't find it anywhere.Looking forward your reply.

**Comment by HenryJunW** [comment]
Hello, thanks for your interest in our work. Please refer to the table in https://github.com/HenryJunW/TAG/blob/main/MODEL_ZOO.md. You can download the generated data from the 'download' of the first row  'st_vqaaug_imdb_train_ocr_en_largest_ocr_bbox_0_4.npy'.
